sourceClusterID: "cluster-csc"
targetClusterID: "cluster-aws"
name: "vxflexos-replication"
driver: "vxflexos"
reclaimPolicy: "Delete"
replicationPrefix: "replication.storage.dell.com"
remoteRetentionPolicy:
  RG: "Delete"
  PV: "Retain"
parameters:
  storagePool: # populate with storage pool to use of arrays
    source: "default"
    target: "default"
  protectionDomain: # populate with protection domain to use of arrays
    source: "default"
    target: "default"
  arrayID: # populate with unique ids of storage arrays
    source: "10cb5e97639c660f"
    target: "033930052b65d90f"
  rpo: "60"
  volumeGroupPrefix: "csi"
  consistencyGroupName: "" # optional name to be given to the rcg
