---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: yelb
  name: redis-pv-claim
  labels:
    app: redis-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: vxflexos-replication
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: yelb
  name: db-pv-claim
  labels:
    app: yelb-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: vxflexos-replication
